apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: echo-server
  name: echo-server
spec:
  replicas: 2
  selector:
    matchLabels:
      run: echo-server
  template:
    metadata:
      labels:
        run: echo-server
    spec:
      containers:
        - image: cdchathura/grpc-server:1.0
          name: simple-server
          env:
            - name: server.port
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: echo-server
  name: echo-server
spec:
  ports:
  - name: grpc-web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: echo-server
  type: ClusterIP
